---

- name: apply base STIG configuration
  hosts: all
  remote_user: root

  roles:
    - base

- name: configure and deploy the webservers and application code
  hosts: webservers
  remote_user: root

  roles:
    - web

