---
- name: V-71901
  lineinfile:
    path: /etc/dconf/db/local.d/00-screensaver
    regexp: 'lock-delay='
    insertafter: '[org/gnome/desktop/screensaver]'
    line: '^lock-delay=uint32 5'
    backup: yes
    state: present
    create: yes
  tags: cat2

