---
- name: V-71953
  lineinfile:
    path: /etc/gdm/custom.conf
    regexp: 'AutomaticLoginEnable'
    insertafter: '[daemon]'
    line: '^AutomaticLoginEnable=false'
    backup: yes
    state: present
    create: yes
  tags: cat2

