---
- name: V-71939
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitEmptyPasswords'
    line: '^PermitEmptyPasswords no'
    backup: yes
    state: present
    create: yes
  tags: cat1

