---
- name: V-71955
  lineinfile:
    path: /etc/gdm/custom.conf
    regexp: 'TimedLoginEnabled'
    insertafter: '[daemon]'
    line: '^TimedLoginEnabled=false'
    backup: yes
    state: present
    create: yes
  tags: cat2

