---
- name: V-71917
  lineinfile:
    path: /etc/security/pwquality.conf
    regexp: 'maxclassrepeat ='
    line: '^maxclassrepeat = 4'
    backup: yes
    state: present
    create: yes
  tags: cat2

