---
- name: V-71959
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'HostbasedAuthentication'
    line: '^HostbasedAuthentication no'
    backup: yes
    state: present
    create: yes
  tags: cat2

