---
- name: V-71957
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'PermitUserEnvironment'
    line: '^PermitUserEnvironment no'
    backup: yes
    state: present
    create: yes
  tags: cat2

