---
- name: V-71983
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: 'blacklist'
    line: '^blacklist usb-storage'
    backup: yes
    state: present
    create: yes
  lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    regexp: 'blacklist'
    line: '^blacklist usb-storage /bin/true'
    backup: yes
    state: present
    create: yes
  tags: cat2

