---
- name: V-72197
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/etc/passwd'
    line: '-w /etc/passwd -p wa -k audit_rules_usergroup_modification'
    backup: yes
    state: present
    create: yes
  tags: cat2

