---
- name: V-72189
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: 'delete_module'
    line: '-a always,exit -F arch=b64 -S delete_module -k module-change'
    backup: yes
    state: present
    create: yes
  tags: cat2

