---
- name: V-72127
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: 'openat'
    line: '-a always,exit -F arch=b64 -S openat -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access'
    backup: yes
    state: present
    create: yes
  tags: cat2

