---
- name: V-72199
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: 'rename'
    line: '-a always,exit -F arch=b64 -S rename -F perm=x -F auid>=1000 -F auid!=4294967295 -k delete'
    backup: yes
    state: present
    create: yes
  tags: cat2

