---
- name: V-72145
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/var/run/faillock'
    line: '-w /var/run/faillock -p wa -k logins'
    backup: yes
    state: present
    create: yes
  tags: cat2

