---
- name: V-72231
  lineinfile:
    path: /etc/sysconfig/authconfig
    regexp: 'useldapauth'
    line: '^USELDAPAUTH = yes'
    backup: yes
    state: present
    create: yes
  lineinfile:
    path: /etc/pam_ldap.conf
    regexp: 'cacertfile'
    line: '^tls_cacertfile /etc/openldap/ldap-cacert.pem'
    backup: yes
    state: present
    create: yes
  tags: cat2

