---
- name: V-72289
  lineinfile:
    path: /etc/sysctl.conf
    regexp: 'net.ipv4.conf.default.accept_redirects ='
    line: '^net.ipv4.conf.default.accept_redirects = 0'
    backup: yes
    state: present
    create: yes
  tags: cat2

