---
- name: V-72171
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: 'mount'
    line: '-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k privileged-mount'
    backup: yes
    state: present
    create: yes
  tags: cat2

