---
- name: V-72227
  lineinfile:
    path: /etc/sysconfig/authconfig
    regexp: 'useldapauth'
    line: '^USELDAPAUTH = yes'
    backup: yes
    state: present
    create: yes
  lineinfile:
    path: /etc/pam_ldap.conf
    regexp: 'ssl'
    line: '^ssl start_tls'
    backup: yes
    state: present
    create: yes
  tags: cat2

