---
- name: V-72149
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/usr/bin/passwd'
    line: '-a always,exit -F path=/usr/bin/passwd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-passwd'
    backup: yes
    state: present
    create: yes
  tags: cat2

