---
- name: V-72091
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: 'space_left_action ='
    line: '^space_left_action = email'
    backup: yes
    state: present
    create: yes
  tags: cat2

