---
- name: V-72093
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: 'action_mail_acct ='
    line: '^action_mail_acct = root'
    backup: yes
    state: present
    create: yes
  tags: cat2

