---
- name: V-72239
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'RhostsRSAAuthentication'
    line: '^RhostsRSAAuthentication no'
    backup: yes
    state: present
    create: yes
  tags: cat2

