---
- name: V-72287
  lineinfile:
    path: /etc/sysctl.conf
    regexp: 'net.ipv4.icmp_echo_ignore_broadcasts='
    line: '^net.ipv4.icmp_echo_ignore_broadcasts=1'
    backup: yes
    state: present
    create: yes
  tags: cat2

