---
- name: V-72135
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/usr/sbin/semanage'
    line: '-a always,exit -F path=/usr/sbin/semanage -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change'
    backup: yes
    state: present
    create: yes
  tags: cat2

