---
- name: V-72175
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/usr/sbin/postdrop'
    line: '-a always,exit -F path=/usr/sbin/postdrop -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-postfix'
    backup: yes
    state: present
    create: yes
  tags: cat2

