---
- name: V-72173
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/bin/umount'
    line: '-a always,exit -F path=/bin/umount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-mount'
    backup: yes
    state: present
    create: yes
  tags: cat2

