---
- name: V-72433
  blockinfile:
    path: /etc/pam_pkcs11/pam_pkcs11.conf
    backup: yes
    create: yes
    state: present
    block: |
      cert_policy =ca, ocsp_on, signature;
      cert_policy =ca, ocsp_on, signature;
      cert_policy =ca, ocsp_on, signature;
  tags: cat2

