---
- name: V-72157
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/usr/sbin/userhelper'
    line: '-a always,exit -F path=/usr/sbin/userhelper -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-passwd'
    backup: yes
    state: present
    create: yes
  tags: cat2

