---
- name: V-72151
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/sbin/unix_chkpwd'
    line: '-a always,exit -F path=/sbin/unix_chkpwd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-passwd'
    backup: yes
    state: present
    create: yes
  tags: cat2

