---
- name: V-72261
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'KerberosAuthentication'
    line: '^KerberosAuthentication no'
    backup: yes
    state: present
    create: yes
  tags: cat2

