---
- name: V-72259
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'GSSAPIAuthentication'
    line: '^GSSAPIAuthentication no'
    backup: yes
    state: present
    create: yes
  tags: cat2

