---
- name: V-72087
  lineinfile:
    path: /etc/audisp/audisp-remote.conf
    regexp: 'disk_full_action ='
    line: '^disk_full_action = single'
    backup: yes
    state: present
    create: yes
  lineinfile:
    path: /etc/audisp/audisp-remote.conf
    regexp: 'network_failure_action ='
    line: '^network_failure_action = single'
    backup: yes
    state: present
    create: yes
  tags: cat2

