---
- name: V-72105
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: ' chmod'
    line: '-a always,exit -F arch=b64 -S chmod -F auid>=1000 -F auid!=4294967295 -k perm_mod'
    backup: yes
    state: present
    create: yes
  tags: cat2

