---
- name: V-72249
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'IgnoreUserKnownHosts'
    line: '^IgnoreUserKnownHosts yes'
    backup: yes
    state: present
    create: yes
  tags: cat2

