---
- name: V-72129
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: 'open_by_handle_at'
    line: '-a always,exit -F arch=b64 -S open_by_handle_at -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access'
    backup: yes
    state: present
    create: yes
  tags: cat2

