---
- name: V-72147
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/var/log/lastlog'
    line: '-w /var/log/lastlog -p wa -k logins'
    backup: yes
    state: present
    create: yes
  tags: cat2

