---
- name: V-72221
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'Ciphers'
    line: '^Ciphers aes128-ctr,aes192-ctr,aes256-ctr'
    backup: yes
    state: present
    create: yes
  tags: cat2

