---
- name: V-72183
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/usr/bin/crontab'
    line: '-a always,exit -F path=/usr/bin/crontab -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-cron'
    backup: yes
    state: present
    create: yes
  tags: cat2

