---
- name: V-72169
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/bin/sudoedit'
    line: '-a always,exit -F path=/bin/sudoedit -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged-priv_change'
    backup: yes
    state: present
    create: yes
  tags: cat2

