---
- name: V-72191
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/sbin/insmod'
    line: '-w /sbin/insmod -p x -F auid!=4294967295 -k module-change'
    backup: yes
    state: present
    create: yes
  tags: cat2

