---
- name: V-72265
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: 'UsePrivilegeSeparation'
    line: '^UsePrivilegeSeparation sandbox'
    backup: yes
    state: present
    create: yes
  tags: cat2

