---
- name: V-73165
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/etc/group'
    line: '-w /etc/group -p wa -k audit_rules_usergroup_modification'
    backup: yes
    state: present
    create: yes
  tags: cat2

