---
- name: V-73175
  lineinfile:
    path: /etc/sysctl.conf
    regexp: 'net.ipv4.conf.all.accept_redirects ='
    line: '^net.ipv4.conf.all.accept_redirects = 0'
    backup: yes
    state: present
    create: yes
  tags: cat2

