---
- name: V-73167
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/etc/gshadow'
    line: '-w /etc/gshadow -p wa -k audit_rules_usergroup_modification'
    backup: yes
    state: present
    create: yes
  tags: cat2

