---
- name: V-73171
  lineinfile:
    path: /etc/audit/rules.d/audit.rules
    regexp: '/etc/shadow'
    line: '-w /etc/shadow -p wa -k audit_rules_usergroup_modification'
    backup: yes
    state: present
    create: yes
  tags: cat2

