---
- name: V-77825
  lineinfile:
    path: /etc/sysctl.conf
    regexp: 'kernel.randomize_va_space'
    line: '^kernel.randomize_va_space=2'
    backup: yes
    state: present
    create: yes
  tags: cat2

