---
- name: V-77819
  lineinfile:
    path: /etc/dconf/db/local.d/00-screensaver
    regexp: 'enable-smartcard-authentication='
    insertafter: '[org/gnome/desktop/screensaver]'
    line: '^enable-smartcard-authentication=true'
    backup: yes
    state: present
    create: yes
  tags: cat2

